# Generated by Django 3.1.4 on 2021-01-18 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movements', '0005_remove_movement_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50, verbose_name='Codigo de factura')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sub total de la facutura')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Iva de la factura')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de la factura')),
                ('pay_from_fund', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='account_fund_bills', to='movements.accountfunds')),
            ],
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['bill_number'], name='index_bill_number'),
        ),
    ]
