# Generated by Django 3.1.4 on 2021-01-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='iva',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Iva de la factura'),
        ),
    ]
