# Generated by Django 3.1.4 on 2021-01-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20210118_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='emit_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de emision'),
        ),
    ]
