# Generated by Django 3.1.4 on 2021-01-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_bill_bill_nulled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_nulled_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Fecha de anulación'),
        ),
    ]
