# Generated by Django 3.1.4 on 2021-01-05 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountFunds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_description', models.CharField(default='Balance princiap', max_length=26, null=True, verbose_name='Denomínación del fondo')),
                ('opened_fund_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de apertura')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total disponible')),
                ('output_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo total usado')),
                ('input_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total de saldo recibido')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='account_funds', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=12)),
                ('transaction_type', models.CharField(choices=[('I', 'Ingreso'), ('O', 'Egresos')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de la transacción')),
                ('amount_before_transaction', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total antes de la transaccion')),
                ('amount_after_transaction', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total despues de la transacción')),
                ('movement_date_register', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Adjuntar mensaje al movimiento')),
                ('funding', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='account_fund_movement', to='movements.accountfunds')),
            ],
        ),
    ]
