# Generated by Django 3.1.4 on 2021-01-05 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountfunds',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_funds', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='funding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_fund_movement', to='movements.accountfunds'),
        ),
    ]
