# Generated by Django 3.1.4 on 2021-01-07 21:56

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0002_auto_20210105_1126'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='movement',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='movement',
            name='from_account_funds',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_account_fund', to='movements.accountfunds'),
        ),
    ]
