# Generated by Django 3.1.4 on 2021-01-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0003_auto_20210107_1756'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='movement',
            managers=[
            ],
        ),
    ]
