# Generated by Django 3.1.4 on 2021-01-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0004_auto_20210108_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='transaction_type',
        ),
    ]
